plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'java'
}

group = 'dev.verno'
version = '1.2.3'

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'com.mojang:minecraft:1.19.2'
    mappings 'net.fabricmc:yarn:1.19.2+build.28:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.19.3'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.77.0+1.19.2'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 17
}

jar {
    from('LICENSE') { rename { "${it}_bellbird" } }
}
